version: 0.2
phases:
  build:
    commands:
      - 'dir'
      - 'C:\unreal\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="%CODEBUILD_SRC_DIR%\Small.uproject" -noP4 -platform=Win64 -clientconfig=Development -allmaps -build -stage -pak -archive -archivedirectory="dist" -cookonthefly -verbose'

artifacts:
  files:
    - dist
  discard-paths: yes

  post_build:
    commands:
      - echo "Build success, artifacted files"

artifacts:
  files:
    - dist
  discard-paths: yes