version: 0.2
phases:
  build:
    commands:
      - 'C:\unreal\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project="%CODEBUILD_SRC_DIR%\Small.uproject" -noP4 -platform=Win64 -clientconfig=Development -allmaps -build -stage -pak -archive -archivedirectory="%CODEBUILD_SRC_DIR%\dist" -cookonthefly -verbose'
      - 'Compress-Archive -Path dist\* -DestinationPath packaged'

artifacts:
  files:
    - packaged.zip
  discard-paths: yes

  post_build:
    commands:
      - echo "Build success, artifacted files"

artifacts:
  files:
    - packaged.zip
  discard-paths: yes
